task_level: 3

testcases:
  -
    scenario: "USA_US101-9_1_T-1"
    max_sim_time: 10.0
    ego:
      original_name: P18
      goal_lane_id: 27
    others:
      names: [P4, P10, P15, P19, P21]
    description: "scenario1"

seed: 98