task_level: 3

testcases:
  -
    scenario: "ZAM_Zip-1_64_T-1"
    max_sim_time: 10.0
    ego:
      original_name: P2
      goal_lane_id: 25
    others:
      names: [P0, P1]
    description: "scenario7"

seed: 98